jobs:
  - name: rsynch-manifest3
    type: manifest
    steps:
      - GET: rsynch-img1
      - GET: triggerrsynch1
      
  - name: rsynch-manifest2
    type: manifest
    steps:
      - GET: rsynch-img2
      - GET: triggerrsynch2
      
  - name: rsynch-manifesttest
    type: manifest
    steps:
      - GET: rsynch-img1
      - GET: rsynch-param1
      - GET: rsynch-replica1
      - GET: rsynch-dopt1
      - GET: triggerrsynch3
     
#  - name: repo-ecsdeploy
 #   type: ecsDeploy
  #  steps:
   #   - GET: repo-manifest2
    #  - GET: repo-ecscluster
    
  #- name: repo-dcldeploy
   # type: dclDeploy
    #steps:
     # - GET: repo-manifest
      #- GET: repo-dclcluster
      #- GET: repo-replica1
    
  #- name: repo-ecsdeploytodcldeploy
   # type: dclDeploy
    #steps:
     # - GET: repo-ecsdeploy
      #- GET: repo-dclcluster
      
#  - name: multimanifest-dcldeploy
 #   type: dclDeploy
  #  steps:
   #   - GET: repo-manifest
    #  - GET: repo-manifest2
     # - GET: repo-dclcluster
      
