triggers:
  - name: triggerrsynch1
    type: trigger
    source:
      message: 'testing trigger jobs in yml'
      
  - name: triggerrsynch2
    type: trigger
    source:
      counter: 1
      
  - name: triggerrsynch3
    type: trigger
    source:
      counter: 1
